---
title: "Life Lessons"
date: 2020-12-20
---
theme: minima
title: Life Lessons
author: Dee
email: example@something.com
description: > # this means to ignore newlines until "baseurl:"
 Important life lessons inclusing life hacks and ways to succeed.

# social links
twitter_username: nef_saaid # DO NOT include the @ character, or else the build will fail!
github_username:  SaadiaShahid19 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
